# Generated by Django 5.0.2 on 2024-02-29 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_delete_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('video', models.URLField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='products.product')),
            ],
        ),
    ]
