# Generated by Django 5.0.2 on 2024-02-29 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
        ('products', '0003_delete_lessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lessons', to='products.product'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.URLField(unique=True),
        ),
    ]
