# Generated by Django 5.0.2 on 2024-02-29 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Lessons',
        ),
    ]
